initializing feature branch with linters
expjazz/toDOList pull request #1
Opened 2020-07-06 13:32 UTC by expjazz

2020-07-08 21:01 UTC, Oghenebrume50 requested changes
### CHANGES REQUIRED

Hi @expjazz @mariosknl nice job done here, the project is coming along very well, :slightly_smiling_face:  I have highlighted a few things that need fixing. 

- Currently, I can make a today with wrong or blank data, for example putting "good boy' as the due date of a todo works perfectly, this should not be. 
Also, see the error highlighted  below 

**Please make changes and request for another review** :slightly_smiling_face: 

**RAPHAEL NORIODE** :mask:

2020-07-08 21:01 UTC, Oghenebrume50 commented on src/helpers.js
> +/* eslint-disable import/no-cycle */
This is an indication that there is a circular dependency in your code, this is not good coding practice, please remove this rule and fix the problem, the affected file is the 'Todolistgenerator' 

[see this](https://stackoverflow.com/questions/51094117/dependency-cycle-detected-import-no-cycle)

2020-07-09 17:17 UTC, whiz25 requested changes
## Nice Progress :+1: 
You have done well fixing issues raised by the previous reviewer. We however, need to fix a few things you missed to address. 
- [x] Inputting a random text as date when creating a project doesn't raise any errors. Make sure you validate the date input. Use HTML date to pick date values.
- [x] It's possible to create a task with empty fields. This should not be happening. Please fix that.

### Martin Afani

2020-07-10 08:35 UTC, expjazz commented
### We made all the requested changes.

- Now we added validations for a valid date in the future.
- Now both Projects and Tasks cannot be valid if they are empty.

2020-07-10 14:07 UTC, shloch requested changes
## Hello @expjazz 

Great job with modification from former TSE
![todo2](https://user-images.githubusercontent.com/40712459/87163184-dc128f00-c2be-11ea-9783-c548e8aa2477.gif)

### [changes required]

In the same continuation please try to also prevent the creation of 'EMPTY' projects 
That's the last thing left in my opinion
![todo](https://user-images.githubusercontent.com/40712459/87163260-fa788a80-c2be-11ea-8d8e-1438214e27aa.gif)

Waiting for the last re-review hopefully

Happy coding

2020-07-10 14:22 UTC, expjazz commented
## Dear TSE, 

#### We already implemented those validations. What I think happened is that the last TSE checked the wrong branch in his local machine (now we deleted that branch). The branch we wanted to merge and still want is the 'featureV1'. I just tested this feature on my end and it worked. 

![image](https://user-images.githubusercontent.com/61479648/87164769-8d093180-c29f-11ea-99cf-f5eaf5b96c0b.png)

2020-07-10 14:52 UTC, shloch approved these changes
### Good to go....i happened to have claimed this request again.......
As per our chat, see you on further projects
![accomplished](https://user-images.githubusercontent.com/40712459/87167755-5e9e4d00-c2c5-11ea-9914-ef442c4e9404.jpg)

Happy coding

2020-07-10 22:50 UTC, merged